### ISSUE TITLE
I would like to contact you

### ISSUE THREAD

**Issue by jaizpuruzin** [husqvarnagroup/smart-garden-gateway-public#11]
This is for @rettichschnidi 

Good morning from San Sebastian, Spain

I am writing to you as I need support for your tools:
https://github.com/rettichschnidi/clang-tidy-misra
or else,
https://github.com/rettichschnidi/clang-misracpp2008
I am a software engineer with more than 5 years of experience in railway projects and I am currently working in the company CEIT trying to launch misra rules "for free" in order to get more experience in the static analysis sector.
I would be very grateful if I could contact you to ask for some support.

Thank you very much and whatever you need from me I would be grateful to give you support or help you.
Here my email to contact me:
[jaizpuruzin@ceit.es](mailto:jaizpuruzin@ceit.es)
I also leave you my linkedin:
https://www.linkedin.com/in/joanes-aizpuru-zinkunegi-a06b86164/

I understand that I can't get it up and running because your programme is not synchronised with the latest versions of clang. So let me see if you can answer me:

Do you remember the version of clang you used?
Also, do you remember the steps you took to get it up and running?

Thank you very much for your answer!

Joanes

**Comment by easybe** [comment]
Please do not spam this space with off-topic questions. It is not hard to find @rettichschnidi's e-mail address. Anyway, he has seen the message.
