### ISSUE TITLE
Home App is empty 

### ISSUE THREAD

**Issue by gerd2005** [husqvarnagroup/smart-garden-gateway-public#4]
Hello,

mostly my Home App Looks like this:
![EE4DE331-0EC8-492B-8614-DEBE5FDB5F54](https://user-images.githubusercontent.com/72799068/178945850-5bffd043-44d6-41d8-a6c1-ed7a15a3adb9.png)

Sometimes, after 2 or More App restarts, it looks like that:
![E1FE4DAE-BE4E-4D16-BD7F-DE2C021B5BA9](https://user-images.githubusercontent.com/72799068/178946074-4bf3d0bc-4b1f-4816-97ed-2f3f415bf3fe.png)

why is the App empty at the First App-start?

**Comment by tsagadar** [comment]
Thanks for reporting this issue. Note that the best way to report a problem with the GARDENA smart system is to use the "feedback" functionality within the GARDENA app.

We were able to reproduce the issue with iOS 15.5 but not with the upcoming iOS 16. We will further investigate and address the issue with our scheduled rework of the HomeKit functionality. These changes will be available latest for next garden season.
